# Generated by Django 6.0.4 on 2026-04-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
