# Generated by Django 6.0.4 on 2026-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='elected_position',
            field=models.CharField(blank=True, choices=[('', 'No position'), ('EXEC_PRES', 'Executive President'), ('EXEC_VP', 'Executive Vice President'), ('EXEC_PARL', 'Executive Parliamentarian'), ('EXEC_SEC', 'Executive Secretary'), ('EXEC_TRES', 'Executive Treasurer'), ('SR_PRES', 'Senior President'), ('SR_VP', 'Senior Vice President'), ('SR_SEC', 'Senior Secretary'), ('JR_PRES', 'Junior President'), ('JR_VP', 'Junior Vice President'), ('JR_SEC', 'Junior Secretary'), ('SO_PRES', 'Sophomore President'), ('SO_VP', 'Sophomore Vice President'), ('SO_SEC', 'Sophomore Secretary'), ('FR_PRES', 'Freshman President'), ('FR_VP', 'Freshman Vice President'), ('FR_SEC', 'Freshman Secretary')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='electionapplication',
            name='e_signature_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='electionapplication',
            name='e_signature_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='electionapplication',
            name='e_signature_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.CharField(blank=True, choices=[('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade')], max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3),
        ),
    ]
