# Generated by Django 6.0.4 on 2026-04-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_member_elected_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
