# Generated by Django 6.0.4 on 2026-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0004_attendancesession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('EXCUSED', 'Excused'), ('UNEXCUSED', 'Unexcused')], default='PRESENT', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='attendance_warning_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
